### ISSUE TITLE
About data/gdb9/incons.json?

### ISSUE THREAD

**Issue by anny0316** [PKUterran/HamNet#1]
Hello, 
Thank you for providing such excellent work. I benefited a lot. I'm a little confused about the file “data/gdb9/incons.json”. I don't know why the data should be processed like this.
“
    with open('data/gdb9/incons.json') as fp:
        incons = json.load(fp)
        left = list(set(range(len(smiles))) - set(incons))
        print('{} / {}'.format(len(left), len(smiles)))
        smiles = [smiles[i] for i in left]
        info_list = [info_list[i] for i in left]
        mol_atom_pos = [mol_atom_pos[i] for i in left]
”
Thank you. I want to hear from you as soon as possible.

**Comment by PKUterran** [comment]
Thank you for your support. We are too busy to notice your comment in time. Sorry for that.
About 2 months before the deadline, we found there is a bug that causes inconsistency between the indices and 3D position of atoms for some molecules, and lots of code should be revised to get it fixed. So we decide to remove the molecules (about 10%) rather than fix the bug.
In our later work (e.g. PhysChem), this bug is fixed by using SDFSupplier in RDKit.

**Comment by anny0316** [comment]
Thank you very much, I got it.
